language: csharp
dist: trusty
before_script:
  - wget -O ~/videoEnrollmentB1.mov https://drive.voiceit.io/files/videoEnrollmentB1.mov
  - wget -O ~/videoEnrollmentB2.mov https://drive.voiceit.io/files/videoEnrollmentB2.mov
  - wget -O ~/videoEnrollmentB3.mov https://drive.voiceit.io/files/videoEnrollmentB3.mov
  - wget -O ~/videoVerificationB1.mov https://drive.voiceit.io/files/videoVerificationB1.mov
  - wget -O ~/videoEnrollmentC1.mov https://drive.voiceit.io/files/videoEnrollmentC1.mov
  - wget -O ~/videoEnrollmentC2.mov https://drive.voiceit.io/files/videoEnrollmentC2.mov
  - wget -O ~/videoEnrollmentC3.mov https://drive.voiceit.io/files/videoEnrollmentC3.mov
  - wget -O ~/enrollmentA1.wav https://drive.voiceit.io/files/enrollmentA1.wav
  - wget -O ~/enrollmentA2.wav https://drive.voiceit.io/files/enrollmentA2.wav
  - wget -O ~/enrollmentA3.wav https://drive.voiceit.io/files/enrollmentA3.wav
  - wget -O ~/verificationA1.wav https://drive.voiceit.io/files/verificationA1.wav
  - wget -O ~/enrollmentC1.wav https://drive.voiceit.io/files/enrollmentC1.wav
  - wget -O ~/enrollmentC2.wav https://drive.voiceit.io/files/enrollmentC2.wav
  - wget -O ~/enrollmentC3.wav https://drive.voiceit.io/files/enrollmentC3.wav
  - wget -O ~/faceEnrollmentB1.mp4 https://drive.voiceit.io/files/faceEnrollmentB1.mp4
  - wget -O ~/faceEnrollmentB2.mp4 https://drive.voiceit.io/files/faceEnrollmentB2.mp4
  - wget -O ~/faceEnrollmentB3.mp4 https://drive.voiceit.io/files/faceEnrollmentB3.mp4
  - wget -O ~/faceVerificationB1.mp4 https://drive.voiceit.io/files/faceVerificationB1.mp4
script:
  - cd Test && cp ../VoiceIt2.cs testcsharp/VoiceIt2.cs && nuget restore && msbuild && cd testcsharp/bin/Debug && mono testcsharp2.exe
after_success:
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1.4
  - cd /home/travis/build/voiceittech/VoiceIt3-C-Sharp/Test && ./release.sh
notifications:
  slack:
    secure: kQzeiUsaorfb5CQH2cYKh4TDJzKxVSRW0eKlI1W66HRnFG+vm2xtAOLwvS9nh0x5Ea3NQfyltNmQPeou+B/4E2uIdhM0xSuTjOFjRzF3qZ/FpC+P5Q643/hzmS1zbM6H8LeFwHbUIy4xsTCABj1+d4RGYjA+FwEdUcW/LS1lmMmHCHEtz0j/v9Irh9VpVn4mUKcYzMTEm7te+sG2IKwK45lQ3l2B9QKx8C+juUB1AQPV4eBJDYN/HnnbJRYzlCjEyBUsqBRhS3ujbWooU6xM+mqk0ixGmQhpgweGN9odp5QczsX3GjBywAn4Dl0v7sXLC4PmhLqJGY3N8GIrIZv4gqlZj54ZLzep90rfIpyX9yluTIvnSU81teraYGdBQmnQ1icQJn7B72tPC9/dxKbURkpnW8r/Lb6XQB1xl+tJmC+/5WAf/SRSe1gc9YCdXfnIJAserEdILjHrLaOCnKTVscdTnn+d3kRSshf4jq4R3SPlAmN/X693lqoRUH9vRHuLtHkO5G7hHkNP6xsxPvFug9lH7xX1hBJLa4A2tuBkwIavnxuw8L8vBJ2S6i0ZJUCYh9zRy9unFEDKsnn226dNYgZSv2D3xBP9Gl+59lpbfDt7Y7glN6zjSXlXKU5MK9DvpZVHcgynF7SqRnxvKy6c5igOupcVsMjd1Fd+nOyE30c=
  email:
    on_success: never
    on_failure: never
